### ISSUE TITLE
Add Minor version support

### ISSUE THREAD

**Issue by Niloys7** [blakewilson/semantic-versioning-plugin#13]
Thanks for this package.
However, I also need to disable the auto-update for minor versions, so I use the conditions below, which work perfectly. 
![CleanShot 2024-07-13 at 02 22 35](https://github.com/user-attachments/assets/56491483-5055-4df8-b25b-3e45b31cfd53)
Is there any plan to add a minor version check to this?

`new EnforceSemVer('my-plugin/my-plugin.php', 'minor');  //optional`

Thanks

**Comment by blakewilson** [comment]
Hey @Niloys7,

Could you describe your use case?

I'm hesitant to add this since this package is focused on enforcing SemVer, and per SemVer spec, a minor update is not a breaking change.

**Comment by Niloys7** [comment]
Yes, you are correct. But I try to work like this.

   - Increase the Major version for backward-incompatible changes, the
   Minor version for added features, and the Patch version for bug fixes.


So, sometimes, adding features (minor) requires changing codes in various
files, which may break things too.
But it's okay. I reread the sember doc and some blog posts to get more
ideas.

Thanks.

**Comment by blakewilson** [comment]
@Niloys7 I'm glad you found something that will work! In that case, I'm going to close this for now as I don't see have plans to incorporate this feature at the moment.
